In [1]:
import numpy as np

In [3]:
a = np.array([34,54,36,16])

In [9]:
a.dtype

dtype('int32')

In [13]:
a.shape

(4,)

In [17]:
a2d = np.array([
    [1,2,3],
    [4,5,6]
])

a2d.dtype

dtype('int32')

In [19]:
a2d.shape

(2, 3)

In [55]:
print("zeros:\n", np.zeros((3, 3)))    # 3x3 matrix of zeros
print('ones:\n',np.ones((2, 4)))   # 2x4 matrix of ones
print("ones:\n", np.ones(5))   # 2x4 matrix of ones
print("eye:\n", np.eye(4))           # 4x4 identity matrix
print("full:\n", np.full((2, 2), 7))  # 2x2 matrix filled with 7
print("random:\n", np.random.rand(3, 3)) # 3x3 matrix with random numbers


zeros:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
ones:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
ones:
 [1. 1. 1. 1. 1.]
eye:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
full:
 [[7 7]
 [7 7]]
random:
 [[0.21259177 0.00293283 0.07667127]
 [0.35679042 0.46109438 0.82303641]
 [0.13329293 0.34999775 0.20770929]]


In [25]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr.shape)  # (2, 3) - shape of the array
print(arr.size)   # 6 - total elements
print(arr.dtype)  # int32 or int64 - data type
print(arr.ndim)   # 2 - number of dimensions

(2, 3)
6
int32
2


In [27]:
np.empty(5)

array([2.12199579e-314, 4.67296746e-307, 3.16202013e-321, 6.95293141e-310,
       1.71740612e+161])

In [57]:
ar = np.array([1,2,3,4,5])
print(ar[1])
print(ar[-1])

2
5


In [65]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [61]:
print(arr[1])
print(arr[-1])
print(arr[0])
print(arr[-2])

[4 5 6]
[4 5 6]
[1 2 3]
[1 2 3]


In [69]:
print(arr[1,2])
print(arr[:,1])  #- all rows, 2nd column


6
[2 5]


In [73]:
ar

array([1, 2, 3, 4, 5])

In [71]:
print(ar[1:4])

[2 3 4]


In [89]:
print(arr[1:3])
print(arr[1:31])
print(arr[1:])
print(arr[1:100])
print(arr[1])
print(arr[:1])
print(arr[2:1])
print(arr[100:1])


[[4 5 6]]
[[4 5 6]]
[[4 5 6]]
[[4 5 6]]
[4 5 6]
[[1 2 3]]
[]
[]


In [93]:
print("1d\n",ar)
print("2d\n",arr)

1d
 [1 2 3 4 5]
2d
 [[1 2 3]
 [4 5 6]]


In [95]:
ar[2] = 20
ar

array([ 1,  2, 20,  4,  5])

In [101]:
new_array = np.arange(1,10).reshape(3,3)
new_array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [103]:
new_array = np.arange(1,10)
new_array

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [123]:
new_array = np.arange(1,5).reshape(2,2)
new_array

array([[1, 2],
       [3, 4]])

array = np.arange(1,16).reshape(5,3)
array               

### array[start_row : end_row : step, start_column : end_column : step]


In [153]:
print(array[:,:])


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]


In [155]:
print(array[1:,:])

[[ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]


In [161]:
ar

array([ 1,  2, 20,  4,  5])

In [165]:
print(ar + 10)

[11 12 30 14 15]


In [167]:
ar * 2

array([ 2,  4, 40,  8, 10])

In [169]:
print(ar * 2)

[ 2  4 40  8 10]


In [175]:
print(np.sin(arr))

[[ 0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155 ]]


In [187]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
print(arr1 + arr2)  # [5 7 9]


[5 7 9]


In [189]:
print(arr1)
print(arr2)
arr1 == arr2

[1 2 3]
[4 5 6]


array([False, False, False])

In [197]:
arr1[arr1 > 2]

array([3])

In [199]:
print(arr1[arr1 >= 2])

[2 3]


In [209]:
np.diff(arr1)

array([1, 1])

In [211]:
np.diff(arr1,2)

array([0])

In [205]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(np.sum(arr))    # 21
print(np.mean(arr))   # 3.5
print(np.max(arr))    # 6
print(np.min(arr))    # 1
print(np.std(arr))    # Standard deviation


21
3.5
6
1
1.707825127659933


In [213]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(np.vstack((a, b)))  # Vertical stack
print(np.hstack((a, b)))  # Horizontal stack


[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [217]:
np.vstack((a,b))

array([[1, 2, 3],
       [4, 5, 6]])

In [219]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6])

In [223]:
arr = np.array([1, 2, 3, 4, 5, 6])
print(np.split(arr, 3))  # Split into 3 parts


[array([1, 2]), array([3, 4]), array([5, 6])]


In [225]:
np.split(arr,2)

[array([1, 2, 3]), array([4, 5, 6])]

In [233]:
np.diff(arr, 10)

array([], dtype=int32)

In [235]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print(np.dot(A, B))  # Matrix multiplication
print(np.linalg.inv(A))  # Inverse of matrix A


[[19 22]
 [43 50]]
[[-2.   1. ]
 [ 1.5 -0.5]]
